version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  # pre_build:
  #   commands:
  #     - eslint *.js
  #     - npm test
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --template-file template.yaml --s3-bucket serverless-api-s3 --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - packaged.yaml